deployment:
  mode: "local"

server:
  address: ":8080"

auth:
  provider: "supabase" # "flexprice" or "supabase"
  secret: "031f6bbed1156eca651d48652c17a5bce727514cc804f185aca207153b2915abb79c0f1b53945915866dc3b63f37ea73aa86fc062f13e6008249e30819f87483"
  supabase:
    url: "https://vnswkuldxqmqhyiewgsq.supabase.co"
    anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuc3drdWxkeHFtcWh5aWV3Z3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTQzOTgyNjgsImV4cCI6MjAyOTk3NDI2OH0.bfyVXH--fR50KeYnzImhFrPJ8VHpw5VDu6uRXohL4as"
    secret: "nIp+WyQlckXXnSvvknaQn7poy/27pLAENjoOPU1wblz2Khh1xqVT5ixmgsAsGKqNN8I3SiVmsyz0JR8XLbOjBw=="

kafka:
  brokers:
    - "localhost:29092"
  consumer_group: "flexprice-consumer-local"
  topic: "events"
  use_sasl: false
  sasl_mechanism: ""
  sasl_user: ""
  sasl_password: ""
  client_id: "flexprice-client-local"

clickhouse:
  address: 127.0.0.1:9000
  tls: false
  username: default
  password: default
  database: flexprice

postgres:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  dbname: flexprice
  sslmode: disable

logging:
  level: "debug"

